---
abstract: 'XS implementation layer for Encoding::FixLatin'
author:
  - 'Grant McLean <grantm@cpan.org>'
build_requires:
  Test::More: 0.90
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Encoding-FixLatin-XS
requires:
  Encoding::FixLatin: 1.03
  perl: 5.014
resources:
  repository: git://github.com/grantm/encoding-fixlatin-xs.git
version: 1.01
